name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: ['gh-readonly-queue/main/*']

jobs:
  fast:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
  slow:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - run: sleep 60

